[admin]
see_own_notes   = true
deadmin_on_join = true

[discord]
rich_main_icon_id = "einstein-engines"

[events]
ramping_average_end_time = 180.0
ramping_average_chaos    = 4.5

[game]
hostname           = "kikil's station"
desc               = "Гениальный сервер на кастомном форке Einstein Engines с кучей новых механик для дополнения ролеплея."
soft_max_players   = 60
lobbyenabled       = true
lobbyduration      = 240

[hub]
tags = "lang:ru,region:eu_e,rp:med"
hub_urls = "https://hub.spacestation14.com/"

[ic]
flavor_text = true

[infolinks]
discord    = "https://discord.gg/E2vPNkRTbu"
github     = "https://github.com/klovik/kikil-station"
website    = "https://klvk.ru/"
bug_report = "https://github.com/klovik/kikil-station"

[net]
max_connections = 1024
tickrate = 30

[netres]
limit = 10.0

[build]
fork_id = "kikil-station"

[server]
rules_file   = "Rules.txt"
rules_header = "ui-rules-header"

[ooc]
enable_during_round = true

[vote]
restart_required_ratio = 0.7
preset_enabled = true
map_enabled = true

#[worldgen]
#enabled = true
